spring:
  application:
    name: web-crawler
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:p6spy:h2:mem:webcrawler;mode=mysql
    username: user
    password: ""
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8000

springdoc:
  swagger-ui:
    urls:
      - name: API Documentation
        url: /docs/api-docs.yaml

# Logging
logging:
  level:
    com.github.muhammadabdurrahman: DEBUG
    org.springframework: INFO
    p6spy: DEBUG

# Rate limiting
# rate limit 60 requests per minute per client IP
rate-limit:
  bucket:
    capacity: 60
    tokens: 60
    refill-period: PT1M  # 1 minute

# Cache
cache:
  ttl: PT6H
  retention-duration: PT168H # 7 days
  eviction:
    cron: 0 0 0 * * * # Every day at midnight

# Retry
retry:
  maxAttempts: 9
  backoff:
    delay: 5000
    multiplier: 2
