openapi: 3.0.1
info:
  title: API Documentation
  version: 1.0.0
tags:
  - name: Crawler
    description: Operations related to web crawling

paths:
  /api/v1/crawler/crawl:
    post:
      tags:
        - Crawler
      summary: Start web crawling
      description: Start a web crawling process with a given starting URL and callback URL.
      requestBody:
        description: Crawl request details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrawlRequest'
            example:
              startingUrl: "https://example.com"
              callbackUrl: "https://example.com/callback"
      responses:
        "202":
          description: Crawling started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlSyncResponse'
      callbacks:
        CrawlCompletionCallback:
          '{$request.body#/callbackUrl}':
            post:
              tags:
                - Crawler
              summary: Crawl Completion Callback
              description: Callback sent when crawling is complete.
              requestBody:
                description: Crawl response payload
                required: true
                content:
                  multipart/form-data:
                    schema:
                      type: object
                      properties:
                        file:
                          type: string
                          format: binary
                          description: JSON file containing the crawl response
                  application/json:
                    schema:
                      $ref: '#/components/schemas/CrawlAsyncResponse'
              responses:
                "200":
                  description: Callback acknowledged
                "500":
                  description: Error processing callback

components:
  schemas:
    CrawlRequest:
      required: [ "callbackUrl", "startingUrl" ]
      type: object
      properties:
        startingUrl:
          type: string
        callbackUrl:
          type: string
    CrawlSyncResponse:
      type: object
      required: [ "correlationId" ]
      properties:
        correlationId:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
    CrawlAsyncResponse:
      type: object
      required: [ "startingUrl", "visitedPages" ]
      properties:
        startingUrl:
          type: string
          example: "https://example.com"
        visitedPages:
          type: array
          items:
            type: object
            required: [ "pageUrl", "hyperlinks" ]
            properties:
              pageUrl:
                type: string
                example: "https://example.com/page1"
              hyperlinks:
                type: array
                items:
                  type: string
                example: [ "https://example.com/page2", "https://example.com/page3" ]